name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name you commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Do nothing
